/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedValuationRouteImport } from './routes/_authenticated/valuation'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedPaybackRouteImport } from './routes/_authenticated/payback'
import { Route as AuthenticatedOkrRouteImport } from './routes/_authenticated/okr'
import { Route as AuthenticatedMarkupRouteImport } from './routes/_authenticated/markup'
import { Route as AuthenticatedKpisRouteImport } from './routes/_authenticated/kpis'
import { Route as AuthenticatedInvestorRouteImport } from './routes/_authenticated/investor'
import { Route as AuthenticatedGrowthRouteImport } from './routes/_authenticated/growth'
import { Route as AuthenticatedFinancialIntelligenceRouteImport } from './routes/_authenticated/financial-intelligence'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDecisionsRouteImport } from './routes/_authenticated/decisions'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedBusinessPlanRouteImport } from './routes/_authenticated/business-plan'
import { Route as AuthenticatedAiAnalystRouteImport } from './routes/_authenticated/ai-analyst'
import { Route as AuthenticatedFinancialIntelligenceIndexRouteImport } from './routes/_authenticated/financial-intelligence.index'
import { Route as AuthenticatedFinancialIntelligenceDreRouteImport } from './routes/_authenticated/financial-intelligence.dre'
import { Route as AuthenticatedFinancialIntelligenceDfcRouteImport } from './routes/_authenticated/financial-intelligence.dfc'
import { Route as AuthenticatedFinancialIntelligenceBreakEvenRouteImport } from './routes/_authenticated/financial-intelligence.break-even'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValuationRoute = AuthenticatedValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaybackRoute = AuthenticatedPaybackRouteImport.update({
  id: '/payback',
  path: '/payback',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOkrRoute = AuthenticatedOkrRouteImport.update({
  id: '/okr',
  path: '/okr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarkupRoute = AuthenticatedMarkupRouteImport.update({
  id: '/markup',
  path: '/markup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKpisRoute = AuthenticatedKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestorRoute = AuthenticatedInvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrowthRoute = AuthenticatedGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialIntelligenceRoute =
  AuthenticatedFinancialIntelligenceRouteImport.update({
    id: '/financial-intelligence',
    path: '/financial-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisionsRoute = AuthenticatedDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessPlanRoute =
  AuthenticatedBusinessPlanRouteImport.update({
    id: '/business-plan',
    path: '/business-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiAnalystRoute = AuthenticatedAiAnalystRouteImport.update({
  id: '/ai-analyst',
  path: '/ai-analyst',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialIntelligenceIndexRoute =
  AuthenticatedFinancialIntelligenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinancialIntelligenceRoute,
  } as any)
const AuthenticatedFinancialIntelligenceDreRoute =
  AuthenticatedFinancialIntelligenceDreRouteImport.update({
    id: '/dre',
    path: '/dre',
    getParentRoute: () => AuthenticatedFinancialIntelligenceRoute,
  } as any)
const AuthenticatedFinancialIntelligenceDfcRoute =
  AuthenticatedFinancialIntelligenceDfcRouteImport.update({
    id: '/dfc',
    path: '/dfc',
    getParentRoute: () => AuthenticatedFinancialIntelligenceRoute,
  } as any)
const AuthenticatedFinancialIntelligenceBreakEvenRoute =
  AuthenticatedFinancialIntelligenceBreakEvenRouteImport.update({
    id: '/break-even',
    path: '/break-even',
    getParentRoute: () => AuthenticatedFinancialIntelligenceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai-analyst': typeof AuthenticatedAiAnalystRoute
  '/business-plan': typeof AuthenticatedBusinessPlanRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/financial-intelligence': typeof AuthenticatedFinancialIntelligenceRouteWithChildren
  '/growth': typeof AuthenticatedGrowthRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/kpis': typeof AuthenticatedKpisRoute
  '/markup': typeof AuthenticatedMarkupRoute
  '/okr': typeof AuthenticatedOkrRoute
  '/payback': typeof AuthenticatedPaybackRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/valuation': typeof AuthenticatedValuationRoute
  '/financial-intelligence/break-even': typeof AuthenticatedFinancialIntelligenceBreakEvenRoute
  '/financial-intelligence/dfc': typeof AuthenticatedFinancialIntelligenceDfcRoute
  '/financial-intelligence/dre': typeof AuthenticatedFinancialIntelligenceDreRoute
  '/financial-intelligence/': typeof AuthenticatedFinancialIntelligenceIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai-analyst': typeof AuthenticatedAiAnalystRoute
  '/business-plan': typeof AuthenticatedBusinessPlanRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/decisions': typeof AuthenticatedDecisionsRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/growth': typeof AuthenticatedGrowthRoute
  '/investor': typeof AuthenticatedInvestorRoute
  '/kpis': typeof AuthenticatedKpisRoute
  '/markup': typeof AuthenticatedMarkupRoute
  '/okr': typeof AuthenticatedOkrRoute
  '/payback': typeof AuthenticatedPaybackRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/valuation': typeof AuthenticatedValuationRoute
  '/': typeof AuthenticatedIndexRoute
  '/financial-intelligence/break-even': typeof AuthenticatedFinancialIntelligenceBreakEvenRoute
  '/financial-intelligence/dfc': typeof AuthenticatedFinancialIntelligenceDfcRoute
  '/financial-intelligence/dre': typeof AuthenticatedFinancialIntelligenceDreRoute
  '/financial-intelligence': typeof AuthenticatedFinancialIntelligenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-analyst': typeof AuthenticatedAiAnalystRoute
  '/_authenticated/business-plan': typeof AuthenticatedBusinessPlanRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/decisions': typeof AuthenticatedDecisionsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/financial-intelligence': typeof AuthenticatedFinancialIntelligenceRouteWithChildren
  '/_authenticated/growth': typeof AuthenticatedGrowthRoute
  '/_authenticated/investor': typeof AuthenticatedInvestorRoute
  '/_authenticated/kpis': typeof AuthenticatedKpisRoute
  '/_authenticated/markup': typeof AuthenticatedMarkupRoute
  '/_authenticated/okr': typeof AuthenticatedOkrRoute
  '/_authenticated/payback': typeof AuthenticatedPaybackRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/valuation': typeof AuthenticatedValuationRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/financial-intelligence/break-even': typeof AuthenticatedFinancialIntelligenceBreakEvenRoute
  '/_authenticated/financial-intelligence/dfc': typeof AuthenticatedFinancialIntelligenceDfcRoute
  '/_authenticated/financial-intelligence/dre': typeof AuthenticatedFinancialIntelligenceDreRoute
  '/_authenticated/financial-intelligence/': typeof AuthenticatedFinancialIntelligenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-analyst'
    | '/business-plan'
    | '/custos'
    | '/decisions'
    | '/documents'
    | '/empresas'
    | '/financial-intelligence'
    | '/growth'
    | '/investor'
    | '/kpis'
    | '/markup'
    | '/okr'
    | '/payback'
    | '/risk'
    | '/timeline'
    | '/valuation'
    | '/financial-intelligence/break-even'
    | '/financial-intelligence/dfc'
    | '/financial-intelligence/dre'
    | '/financial-intelligence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai-analyst'
    | '/business-plan'
    | '/custos'
    | '/decisions'
    | '/documents'
    | '/empresas'
    | '/growth'
    | '/investor'
    | '/kpis'
    | '/markup'
    | '/okr'
    | '/payback'
    | '/risk'
    | '/timeline'
    | '/valuation'
    | '/'
    | '/financial-intelligence/break-even'
    | '/financial-intelligence/dfc'
    | '/financial-intelligence/dre'
    | '/financial-intelligence'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-analyst'
    | '/_authenticated/business-plan'
    | '/_authenticated/custos'
    | '/_authenticated/decisions'
    | '/_authenticated/documents'
    | '/_authenticated/empresas'
    | '/_authenticated/financial-intelligence'
    | '/_authenticated/growth'
    | '/_authenticated/investor'
    | '/_authenticated/kpis'
    | '/_authenticated/markup'
    | '/_authenticated/okr'
    | '/_authenticated/payback'
    | '/_authenticated/risk'
    | '/_authenticated/timeline'
    | '/_authenticated/valuation'
    | '/_authenticated/'
    | '/_authenticated/financial-intelligence/break-even'
    | '/_authenticated/financial-intelligence/dfc'
    | '/_authenticated/financial-intelligence/dre'
    | '/_authenticated/financial-intelligence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valuation': {
      id: '/_authenticated/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof AuthenticatedValuationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payback': {
      id: '/_authenticated/payback'
      path: '/payback'
      fullPath: '/payback'
      preLoaderRoute: typeof AuthenticatedPaybackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/okr': {
      id: '/_authenticated/okr'
      path: '/okr'
      fullPath: '/okr'
      preLoaderRoute: typeof AuthenticatedOkrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markup': {
      id: '/_authenticated/markup'
      path: '/markup'
      fullPath: '/markup'
      preLoaderRoute: typeof AuthenticatedMarkupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kpis': {
      id: '/_authenticated/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof AuthenticatedKpisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investor': {
      id: '/_authenticated/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof AuthenticatedInvestorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/growth': {
      id: '/_authenticated/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof AuthenticatedGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial-intelligence': {
      id: '/_authenticated/financial-intelligence'
      path: '/financial-intelligence'
      fullPath: '/financial-intelligence'
      preLoaderRoute: typeof AuthenticatedFinancialIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisions': {
      id: '/_authenticated/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AuthenticatedDecisionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-plan': {
      id: '/_authenticated/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof AuthenticatedBusinessPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-analyst': {
      id: '/_authenticated/ai-analyst'
      path: '/ai-analyst'
      fullPath: '/ai-analyst'
      preLoaderRoute: typeof AuthenticatedAiAnalystRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financial-intelligence/': {
      id: '/_authenticated/financial-intelligence/'
      path: '/'
      fullPath: '/financial-intelligence/'
      preLoaderRoute: typeof AuthenticatedFinancialIntelligenceIndexRouteImport
      parentRoute: typeof AuthenticatedFinancialIntelligenceRoute
    }
    '/_authenticated/financial-intelligence/dre': {
      id: '/_authenticated/financial-intelligence/dre'
      path: '/dre'
      fullPath: '/financial-intelligence/dre'
      preLoaderRoute: typeof AuthenticatedFinancialIntelligenceDreRouteImport
      parentRoute: typeof AuthenticatedFinancialIntelligenceRoute
    }
    '/_authenticated/financial-intelligence/dfc': {
      id: '/_authenticated/financial-intelligence/dfc'
      path: '/dfc'
      fullPath: '/financial-intelligence/dfc'
      preLoaderRoute: typeof AuthenticatedFinancialIntelligenceDfcRouteImport
      parentRoute: typeof AuthenticatedFinancialIntelligenceRoute
    }
    '/_authenticated/financial-intelligence/break-even': {
      id: '/_authenticated/financial-intelligence/break-even'
      path: '/break-even'
      fullPath: '/financial-intelligence/break-even'
      preLoaderRoute: typeof AuthenticatedFinancialIntelligenceBreakEvenRouteImport
      parentRoute: typeof AuthenticatedFinancialIntelligenceRoute
    }
  }
}

interface AuthenticatedFinancialIntelligenceRouteChildren {
  AuthenticatedFinancialIntelligenceBreakEvenRoute: typeof AuthenticatedFinancialIntelligenceBreakEvenRoute
  AuthenticatedFinancialIntelligenceDfcRoute: typeof AuthenticatedFinancialIntelligenceDfcRoute
  AuthenticatedFinancialIntelligenceDreRoute: typeof AuthenticatedFinancialIntelligenceDreRoute
  AuthenticatedFinancialIntelligenceIndexRoute: typeof AuthenticatedFinancialIntelligenceIndexRoute
}

const AuthenticatedFinancialIntelligenceRouteChildren: AuthenticatedFinancialIntelligenceRouteChildren =
  {
    AuthenticatedFinancialIntelligenceBreakEvenRoute:
      AuthenticatedFinancialIntelligenceBreakEvenRoute,
    AuthenticatedFinancialIntelligenceDfcRoute:
      AuthenticatedFinancialIntelligenceDfcRoute,
    AuthenticatedFinancialIntelligenceDreRoute:
      AuthenticatedFinancialIntelligenceDreRoute,
    AuthenticatedFinancialIntelligenceIndexRoute:
      AuthenticatedFinancialIntelligenceIndexRoute,
  }

const AuthenticatedFinancialIntelligenceRouteWithChildren =
  AuthenticatedFinancialIntelligenceRoute._addFileChildren(
    AuthenticatedFinancialIntelligenceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAnalystRoute: typeof AuthenticatedAiAnalystRoute
  AuthenticatedBusinessPlanRoute: typeof AuthenticatedBusinessPlanRoute
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedDecisionsRoute: typeof AuthenticatedDecisionsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedFinancialIntelligenceRoute: typeof AuthenticatedFinancialIntelligenceRouteWithChildren
  AuthenticatedGrowthRoute: typeof AuthenticatedGrowthRoute
  AuthenticatedInvestorRoute: typeof AuthenticatedInvestorRoute
  AuthenticatedKpisRoute: typeof AuthenticatedKpisRoute
  AuthenticatedMarkupRoute: typeof AuthenticatedMarkupRoute
  AuthenticatedOkrRoute: typeof AuthenticatedOkrRoute
  AuthenticatedPaybackRoute: typeof AuthenticatedPaybackRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedValuationRoute: typeof AuthenticatedValuationRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAnalystRoute: AuthenticatedAiAnalystRoute,
  AuthenticatedBusinessPlanRoute: AuthenticatedBusinessPlanRoute,
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedDecisionsRoute: AuthenticatedDecisionsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedFinancialIntelligenceRoute:
    AuthenticatedFinancialIntelligenceRouteWithChildren,
  AuthenticatedGrowthRoute: AuthenticatedGrowthRoute,
  AuthenticatedInvestorRoute: AuthenticatedInvestorRoute,
  AuthenticatedKpisRoute: AuthenticatedKpisRoute,
  AuthenticatedMarkupRoute: AuthenticatedMarkupRoute,
  AuthenticatedOkrRoute: AuthenticatedOkrRoute,
  AuthenticatedPaybackRoute: AuthenticatedPaybackRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedValuationRoute: AuthenticatedValuationRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
